/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;
import Main.main;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;
import java.io.File;  
import java.io.FileNotFoundException;  
import java.util.Scanner; 
import org.graphstream.graph.*;
import org.graphstream.graph.implementations.*;
import org.graphstream.ui.graphicGraph.*;
import estructuras.Nodo;

/**
 *
 * @author truenno
 */
public class Main_interface extends javax.swing.JFrame {

public static Graph grafo = new SingleGraph("Red Social");
	/**
	 * Creates new form FIle_Chooser
	 */
	public Main_interface() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the
	 * form. WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jPanel2 = new javax.swing.JPanel();
                jButton1 = new javax.swing.JButton();
                leer_archivo = new javax.swing.JButton();
                jLabel1 = new javax.swing.JLabel();
                jButton3 = new javax.swing.JButton();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

                jButton1.setText("Ver Grafo");
                jButton1.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jButton1ActionPerformed(evt);
                        }
                });

                leer_archivo.setText("Cargar datos de usuarios");
                leer_archivo.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                leer_archivoActionPerformed(evt);
                        }
                });

                jLabel1.setFont(new java.awt.Font("sansserif", 0, 36)); // NOI18N
                jLabel1.setText("Bienvenido al Sistema");

                jButton3.setText("Modificar datos de usuario");
                jButton3.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jButton3ActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
                jPanel2.setLayout(jPanel2Layout);
                jPanel2Layout.setHorizontalGroup(
                        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(93, 93, 93)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(leer_archivo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButton3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap(115, Short.MAX_VALUE))
                );
                jPanel2Layout.setVerticalGroup(
                        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(52, 52, 52)
                                .addComponent(jLabel1)
                                .addGap(73, 73, 73)
                                .addComponent(jButton1)
                                .addGap(30, 30, 30)
                                .addComponent(leer_archivo)
                                .addGap(33, 33, 33)
                                .addComponent(jButton3)
                                .addContainerGap(83, Short.MAX_VALUE))
                );

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                );

                pack();
        }// </editor-fold>//GEN-END:initComponents

        private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

		
        }//GEN-LAST:event_jButton3ActionPerformed

        private void leer_archivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_leer_archivoActionPerformed
                // TODO add your handling code here:
		// damn bro thats crazy
		JFileChooser fileChooser = new JFileChooser();
		fileChooser.setCurrentDirectory(new File(System.getProperty("user.home")));
		FileNameExtensionFilter filter = new FileNameExtensionFilter("Text Files", "txt");
		fileChooser.setFileFilter(filter);
		int result = fileChooser.showOpenDialog(jPanel2);
		File selectedFile = fileChooser.getSelectedFile();
		try {
			Scanner lector = new Scanner(selectedFile);
			System.out.println("Seleccion Exitosa, Ubicacion:" + selectedFile);
			StringBuilder data = new StringBuilder();
			while (lector.hasNextLine()) {
				String data_ln = lector.nextLine();
				data.append(data_ln);
				}
				String usuarios_split = data.toString().split("relaciones")[0];
				String[] usuarios_split2 = usuarios_split.split("usuarios");
				String[] usuarios_split3 = usuarios_split2[1].split("@");
				for (int i =1; i < usuarios_split3.length; i++) {
					String to_insert = "@" + usuarios_split3[i];
					main.lista_usuarios.InsertLast(to_insert);
				
			}

				String relaciones_split = data.toString().split("relaciones")[1];
				String[] wait = relaciones_split.split("@");
				for (int i = 1; i < wait.length; i++) {
				if (wait[i] != null && wait[i+1] != null){
					String to_insert = "@"+ wait[i] + "@"+ wait[i+1];
					main.lista_relaciones.InsertLast(to_insert);
					i++;
				}		
			}


		}catch (Exception FileNotFoundException) {
		System.out.println("Seleccion Fallida, Intentelo de Nuevo");
			System.out.println("lol");
	}
		
		
		
        }//GEN-LAST:event_leer_archivoActionPerformed

        private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
                // TODO add your handling code here:
		//not coding more like coping so hard ;-;
		grafo.setStrict(false);
		grafo.setAutoCreate(true);

		for (Nodo pAux = main.lista_usuarios.getpFirst() ; pAux !=null; pAux = pAux.getPnext() ) {
			grafo.addNode(pAux.getData().toString()).setAttribute("ui.label", pAux.getData().toString());
		}
		for (Nodo pAux = main.lista_relaciones.getpFirst() ; pAux !=null; pAux = pAux.getPnext() ) {
			String[] to_insert = pAux.getData().toString().split(", ");
			grafo.addEdge(to_insert[0]+to_insert[1], to_insert[0], to_insert[1]);
		}
		grafo.setAttribute("ui.stylesheet", "node{\n" +
                "    size: 30px, 30px;\n" +
                "    fill-color: #000000;\n" +
                "    text-mode: normal; \n" +
                "    text-size: 15px; \n" +
                "}");
		grafo.display();


		
        }//GEN-LAST:event_jButton1ActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(Main_interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(Main_interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(Main_interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(Main_interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new Main_interface().setVisible(true);
			}
		});
	}

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton jButton1;
        private javax.swing.JButton jButton3;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JPanel jPanel2;
        private javax.swing.JButton leer_archivo;
        // End of variables declaration//GEN-END:variables
}
